# Generated by Django 3.2.3 on 2021-05-29 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_korean', models.CharField(default='1 Сабақ. ', max_length=100, unique=True)),
                ('title_kazakh', models.CharField(max_length=100)),
                ('order', models.IntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'Сабақ',
                'verbose_name_plural': 'Сабақтар',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TopicWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name_korean', models.CharField(max_length=100, unique=True)),
                ('topic_name_kazakh', models.CharField(max_length=100, unique=True)),
                ('order', models.IntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'Тақырып',
                'verbose_name_plural': 'Тақырыптар',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_korean', models.CharField(max_length=100, unique=True)),
                ('word_kazakh', models.CharField(max_length=100, unique=True)),
                ('part_of_speech', models.CharField(choices=[('Зат', 'Зат есім'), ('Сын', 'Сын есім'), ('Сан', 'Сан есім'), ('Ес', 'Есімдік'), ('Ет', 'Етістік'), ('Ү', 'Үстеу'), ('Еліктеу', 'Еліктеу сөздер'), ('Ш', 'Шылау'), ('О', 'Одағай')], default='Зат есім', max_length=100)),
                ('transcription', models.CharField(default='[]', max_length=150)),
                ('example_korean_one', models.CharField(max_length=250)),
                ('example_kazakh_one', models.CharField(max_length=250)),
                ('example_korean_two', models.CharField(max_length=250)),
                ('example_kazakh_two', models.CharField(max_length=250)),
                ('example_korean_three', models.CharField(max_length=250)),
                ('example_kazakh_three', models.CharField(max_length=250)),
                ('audio', models.FileField(blank=True, upload_to='audio/')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnkorean.lesson')),
                ('topic_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnkorean.topicword')),
            ],
            options={
                'verbose_name': 'Сөз',
                'verbose_name_plural': 'Сөздер',
            },
        ),
    ]
