# Generated by Django 3.2.3 on 2021-05-29 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learnkorean', '0002_alter_word_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grammar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_korean', models.CharField(max_length=100, unique=True)),
                ('rule_kazakh', models.CharField(max_length=100, unique=True)),
                ('general_rule', models.CharField(max_length=255, unique=True)),
                ('example_korean_one', models.CharField(max_length=250)),
                ('example_kazakh_one', models.CharField(max_length=250)),
                ('example_korean_two', models.CharField(max_length=250)),
                ('example_kazakh_two', models.CharField(max_length=250)),
                ('example_korean_three', models.CharField(max_length=250)),
                ('example_kazakh_three', models.CharField(max_length=250)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnkorean.lesson')),
            ],
            options={
                'verbose_name': 'Грамматика',
                'verbose_name_plural': 'Грамматика жинағы',
            },
        ),
    ]
