# Generated by Django 3.2.3 on 2021-05-29 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learnkorean', '0003_grammar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grammar',
            options={'verbose_name': 'Грамматика', 'verbose_name_plural': 'Грамматикалар'},
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dialogue_korean', models.CharField(max_length=100, unique=True)),
                ('dialogue_kazakh', models.CharField(max_length=100, unique=True)),
                ('audio', models.FileField(upload_to='')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnkorean.lesson')),
            ],
            options={
                'verbose_name': 'Оқылым',
                'verbose_name_plural': 'Оқылымдар',
            },
        ),
    ]
