# Generated by Django 3.2.3 on 2021-05-29 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learnkorean', '0007_quiz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'Жаттығу', 'verbose_name_plural': 'Жаттығулар'},
        ),
    ]
