# Generated by Django 3.2.3 on 2021-05-29 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learnkorean', '0009_category_favorire_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='data',
        ),
    ]
