# Generated by Django 3.2.3 on 2021-05-29 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learnkorean', '0012_auto_20210529_1719'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name': 'Сөз', 'verbose_name_plural': 'Менің сөздігім'},
        ),
    ]
